name: Daily SJTU News Watchdog

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0点 (北京时间 8点)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Main Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SJTU_new: ${{ secrets.SJTU_NEW }}
          
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          
        run: python main.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          git add .
          
          git commit -m "Auto-update daily news data" || echo "No changes to commit"
  
          git push